[Network]
#type rpc or channel
Type="channel"
CAFile="./ca.crt"
Cert="./sdk.crt"
Key="./sdk.key"
[[Network.Connection]]
NodeURL="127.0.0.1:20200"
GroupID=1
# [[Network.Connection]]
# NodeURL="127.0.0.1:20200"
# GroupID=2

[Account]
# only support PEM format for now
KeyFile="./accounts/0x48eac900f9e862c94e1e38ec205b6a991a349217.pem"

[Chain]
ChainID=1
SMCrypto=false